spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/vacationable
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true


  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    org.flywaydb: DEBUG