spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/vacationable
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    schemas: vacationable
    default-schema: vacationable

jwt:
  secret: ${JWT_SECRET:ThisIsAVerySecureSecretKeyWith32CharacterLength1234}
  expiration: 86400000